[name]
type = "string"

GRO = "The first line of a GRO file is used as the frame **name** when reading."
SDF = "The first line of an SDF file is used as the frame **name** when reading."
MOL2 = "The first line after ``@<TRIPOS>MOLECULE`` is used as the frame **name** when reading."
